package com.docusign.report.common.constant;

public enum FailureStep {

	CALLING_DS_API,
	COPYING_DB_DATA_TO_CSV,
	SAVING_REPORT_DATA_IN_DB,
	JOINING_ALL_ACCOUNT_FUTURE,
	JOINING_ALL_PAGES_ACCOUNT_FUTURE,
	EVALUATE_JS_FUNCTION_EXPRESSION,
	OUTER_JSON_FILTER_PROCESSING,
	PROCESSROWDATAASYNC,
	PROCESSROWDATAFORASYNC,
	PROCESSENVDATAFORWRITINGARCHIVE,
	PROCESSENVDATAFORWRITINGNONARCHIVE,
	OUTER_JSON_FILTER_PROCESSING_SUPPLYSYNC,
	SPLITTING_WRITING_TO_CSV,
	PREPARE_API_URI,
	PROCESSDSAPICALLERROREXCEPTION;
}