CREATE TABLE reportdb.dbo.reportdata (
	createddatetime bigint NOT NULL,
	createdby varchar(100) NOT NULL,
	sendername varchar(200) NOT NULL,
	senderemail varchar(200) NOT NULL,
	sentdate bigint NOT NULL,
	recipientcount bigint NOT NULL,
	documentcount bigint NOT NULL,
	pagescount bigint NOT NULL,
	status varchar(100) NOT NULL,
	completeddate bigint NULL,
	billable varchar(100) NULL,
	completionrate bigint NULL,
	completionvelocity varchar(100) NULL,
	greenimpact bigint NULL,
	recordid varchar(100) NOT NULL,
	accountid varchar(100) NOT NULL,
	batchid varchar(100) NOT NULL,
	processid varchar(100) NOT NULL,
	ecf varchar(1000) NULL,
	employeeid varchar(100) NULL,
	envelopeid varchar(100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	CONSTRAINT reportdata_PK PRIMARY KEY (rowid)
) GO